# W2_D2_Session6_Assignment_4.11442

### Problem 1

#### Method #1

In [14]:
import numpy as np

In [15]:
#This function uses the vander function from numpy
def getMatrixFromVector(vector, N, increasing = False):
    matrix = np.vander(vector, N, increasing)
        
    return matrix

In [16]:
#In below code example setting increasing to False, and print resultant matrix based on N-i-1 condition.
getMatrixFromVector(np.array([1, 2, 3, 4]), 4, increasing=False)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [17]:
#In below code example setting increasing to True, we are starting the power value from 0.
getMatrixFromVector(np.array([1, 2, 3, 4]), 4, increasing=True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

#### Method #2

In [18]:
#This function uses the column_stack function from numpy
def getMatrixFromVector(vector, N, increasing = False):
    if(increasing):
        matrix = np.column_stack(vector**i for i in range(N))
    else:
        matrix = np.column_stack(vector**(N-i-1) for i in range(N))
        
    return matrix

In [21]:
#In below code example setting increasing to True, we are starting the power value from 0.
getMatrixFromVector(np.array([1, 2, 3, 4]), 4, increasing=False)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [22]:
#In below code example setting increasing to False, and print resultant matrix based on N-i-1 condition.
getMatrixFromVector(np.array([1, 2, 3, 4]), 4, increasing=True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])